### ISSUE TITLE
Newsletter release checklist

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3254]
- [ ] Uploaded to tridactyl.xyz (apparently I put it there so people could have an RSS feed but then I completely forgot to a) tell anyone b) remember to keep it up to date c) remember it existed)
- [ ] Sent to Patreon sponsors
- [ ] Sent to GitHub sponsors

**Comment by bovine3dom** [comment]
Running into an issue with the site so it will fall behind on newsletters until fixed: https://github.com/tridactyl/site/issues/9
